export default {
  image: require('../../../../assets/images/mannequin.jpg'),
  imageWidth: 561,
  imageHeight: 1563,
  spots: [
    {
      x: '50%',
      y: '17.1%',
      w: '20%',
      name: 'neck',
    },
    {
      x: '72%',
      y: '19%',
      w: '20%',
      rotate: '27deg',
      name: 'shoulder',
    },
    {
      x: '50%',
      y: '23%',
      w: '51%',
      name: 'carrure',
    },
    {
      x: '50%',
      y: '26%',
      w: '45%',
      name: 'emmanchure',
    },
    {
      x: '50%',
      y: '29.5%',
      w: '40%',
      name: 'bust',
    },
    {
      x: '-5%',
      y: '29%',
      w: '51%',
      rotate: '-90deg',
      name: 'frontLength',
    },
    {
      x: '100%',
      y: '26%',
      w: '33%',
      rotate: '90deg',
      name: 'bustLength',
    },
    {
      x: '50%',
      y: '36.5%',
      w: '30%',
      name: 'waist',
    },
    {
      x: '49.5%',
      y: '41%',
      w: '39%',
      name: 'smallHips',
    },
    {
      x: '49.5%',
      y: '44.5%',
      w: '44%',
      name: 'basin',
    },
    {
      x: '92%',
      y: '36%',
      w: '70%',
      rotate: '81deg',
      name: 'armLength',
    },
    {
      x: '19%',
      y: '43%',
      w: '22%',
      rotate: '-90deg',
      name: 'basinHeight',
    },
    {
      x: '-5%',
      y: '55.5%',
      w: '90%',
      rotate: '-90deg',
      name: 'skirtLength',
    },
  ],
};
